name: 'Terraform API'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform-production:
    name: 'Production'
#    needs: [terraform-development, terraform-staging]
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      uses: kvrhdn/tfe-run@v1
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        organization: hashidemos
        workspace: fancy-app-production
        type: plan
        message: |
          GitHub Action run triggered using tfe-run (commit: ${{ github.SHA }})
        wait-for-completion: true
      id: tfe-plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: kvrhdn/tfe-run@v1
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        organization: hashidemos
        workspace: fancy-app-production
        type: apply
        message: |
          GitHub Action run triggered using tfe-run (commit: ${{ github.SHA }})
        wait-for-completion: true
      id: tfe-apply

    - name: Get Terraform Cost Estimate
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        TFC_RUN_ID=`echo "${{ steps.tfe-apply.outputs.run-url }}" | grep -oE 'run-[a-zA-Z0-9]+'`
        echo $TFC_RUN_ID
        COST_ESTIMATE_ID=`curl https://app.terraform.io/api/v2/runs/$TFC_RUN_ID -H "Content-Type: application/vnd.api+json" -H "Accept: application/vnd.api+json" -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" | jq -r '.data.relationships."cost-estimate".data.id'`
        curl https://app.terraform.io/api/v2/cost-estimates/$COST_ESTIMATE_ID -H "Content-Type: application/vnd.api+json" -H "Accept: application/vnd.api+json" -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" 